name: flutterteams
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^2.5.1
  cupertino_icons: ^1.0.2
  firebase_core: ^1.6.0
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0
  ionicons: ^0.1.2
  lottie: ^1.1.0
  responsive_builder: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
